language: python
python:
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install pytest-cov
  - pip install codecov

script:
  - py.test --cov=./

after_success:
  - codecov
